# Generated by Django 5.2.7 on 2025-11-11 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='上司承認日時')),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='人事承認日時')),
                ('application_type', models.CharField(choices=[('paid_leave', '有給休暇'), ('late', '遅刻'), ('early_leave', '早退'), ('absence', '欠勤'), ('business_trip', '出張'), ('remote', '在宅勤務'), ('ather', 'その他')], max_length=50, verbose_name='申請種別')),
                ('reason', models.TextField(verbose_name='申請理由')),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('status', models.CharField(choices=[('pending_manager', '上司申請待ち'), ('pending_hr', '人事申請待ち'), ('approved', '承認済'), ('rejected', '却下')], default='pending_manager', max_length=50, verbose_name='ステータス')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='却下理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
                ('hr_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approved_applications', to=settings.AUTH_USER_MODEL, verbose_name='人事承認者')),
                ('manager_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_applications', to=settings.AUTH_USER_MODEL, verbose_name='上司承認者')),
            ],
            options={
                'verbose_name': '各種申請',
                'verbose_name_plural': '各種申請',
                'ordering': ['-created_at'],
            },
        ),
    ]
