# Generated by Django 5.2.7 on 2025-11-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending_manager', '上司承認待ち'), ('pending_hr', '人事承認待ち'), ('approved', '承認済'), ('rejected', '却下'), ('send_back', '差し戻し')], default='pending_manager', max_length=50, verbose_name='ステータス'),
        ),
    ]
