# Generated by Django 5.2.7 on 2025-10-31 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='日付')),
                ('clock_in', models.DateTimeField(blank=True, null=True, verbose_name='出勤時刻')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('total_work_time', models.DurationField(blank=True, null=True, verbose_name='実働時間')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='社員')),
            ],
            options={
                'verbose_name': '勤怠記録',
                'verbose_name_plural': '勤怠記録',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='休憩開始')),
                ('end_time', models.DateTimeField(verbose_name='休憩終了')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendancerecord', verbose_name='勤怠記録')),
            ],
            options={
                'verbose_name': '休憩記録',
                'verbose_name_plural': '休憩記録',
            },
        ),
    ]
