# Generated by Django 5.2.7 on 2025-11-03 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='既読'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_records', to=settings.AUTH_USER_MODEL, verbose_name='確認者'),
        ),
    ]
