# Generated by Django 5.2.7 on 2025-11-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_is_read_attendancerecord_read_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='休憩終了'),
        ),
    ]
